import type { LooseObject, Merge } from 'shared/types';
import { array_normalize, ERR, rAF } from 'shared/utils';
import { EventEmitter } from './event-emitter';

// #region timer
/** Timestamps of elapsed frames */
export type TimerRecords = number[]; // TODO: use `Float64Array` to optimize memory
export type Timer = {
  /**
   * If called in {@link window.requestAnimationFrame rAF} callback or microtasks
   * generated by rAF callback, the start time (the first element of
   * {@link TimerRecords timer records}) will be the current frame time,
   * otherwise the next frame time.
   *
   * @example
   *
   * Do not repeat
   *
   * ```ts
   * timer.start();
   * timer.start(); // error
   *
   * await timer.start();
   * timer.start(); // right
   *
   * timer.start();
   * timer.stop();
   * timer.start(); // right
   * ```
   */
  start(onFrame?: (time: number) => void): Promise<TimerRecords>;
  stop(): void;
};

/**
 * - `undefined`: waiting for launching
 * - `0`: not in frame
 * - Other number: current frame time
 */
let currentFrameTime: number;
const setCurrentFrameTime = (time: number) => (
  (currentFrameTime = time),
  setTimeout(() => (currentFrameTime = 0)), // reset after render pipeline
  rAF(setCurrentFrameTime)
);
/**
 * Create {@link requestAnimationFrame rAF} timer
 *
 * @example Basic usage
 *
 * ```ts
 * const frame_ms = 16.67;
 * const duration = 100;
 * const timer = createTimer(
 *   (time, records) => time - records[0] >= duration - frame_ms / 2,
 * );
 * ```
 */
export const createTimer = (
  /**
   * Return true to stop timer
   *
   * @param time Current frame time
   * @param records History frame times, whose elements represent the start time
   *   of each frame that triggers VSync
   */
  shouldStop: (time: number, records: TimerRecords) => boolean,
) => {
  currentFrameTime ?? setCurrentFrameTime(0); // launch rAF listener, only once
  const timer: Timer = {
    start: (cb) =>
      new Promise((resolve) => {
        const records: number[] = [];
        // if called in frame, add current frame time as the first
        if (currentFrameTime) {
          records.push(currentFrameTime);
          cb?.(currentFrameTime);
        }

        const frame = (time: number) => {
          const is_stoped = shouldStop(time, records);
          records.push(time);
          if (is_stoped) {
            timer.stop();
          } else {
            handle = rAF(frame);
            cb?.(time);
          }
        };
        let handle = rAF(frame);
        timer.stop = () => {
          records.pop();
          cancelAnimationFrame(handle);
          resolve(records);
        };
      }),
    stop() {},
  };
  return timer;
};
// #endregion

// #region component
export type NodeLike = string | Node;
type BuiltinData = {
  /**
   * History frame times, whose elements represent the start time of each frame
   * that triggers VSync
   */
  frame_times: TimerRecords;
  /** Real show duration */
  duration: number;
};
type ForbiddenData = { [K in keyof BuiltinData]?: never };
/**
 * Only called once when the scene is created.
 *
 * @param props - The reactive props to control the scene display
 * @see {@link Scene}
 */
export type Component<
  //eslint-disable-next-line @typescript-eslint/no-explicit-any -- Required for disable contravariance
  P extends LooseObject = any,
  D extends LooseObject = LooseObject & ForbiddenData,
> = {
  (props: P):
    | NodeLike
    | NodeLike[]
    | {
        /** The node(s) appended to the root element of scene */
        node: NodeLike | NodeLike[];
        /** Data getter to get data from elements */
        data: () => D;
      };
};
type GenericComponent<
  P extends LooseObject = LooseObject,
  D extends LooseObject = LooseObject & ForbiddenData,
> = (
  patchProps?: Partial<P>,
  /** NOTE: only for type hint */
  __rawProps?: P,
) => Promise<Merge<D, BuiltinData>>;
/**
 * Provide type infer for generic component, do nothing in runtime.
 *
 * @example
 *
 * Support generic component
 *
 * ```ts
 * using scene = new Scene(
 *   generic(<T>(props: T) => ({ node: [], data: () => props })),
 *   //...
 * );
 * const data = await scene.show({ text: 'hello' });
 * data; // expect: { text: string }
 * ```
 */
export const generic: {
  <P extends LooseObject, D extends LooseObject & ForbiddenData = {}>(
    f: Component<P, D>,
  ): GenericComponent<P, D>;
} = (f) =>
  //@ts-expect-error impl generic component
  f;
/** @ignore */
export type MaybeGenericComponent<
  //eslint-disable-next-line @typescript-eslint/no-explicit-any -- Required for disable contravariance
  P extends LooseObject = any,
  D extends LooseObject & ForbiddenData = {},
> = Component<P, D> | GenericComponent<P, D>;
// #endregion

// #region context
const sceneStack: Scene<MaybeGenericComponent>[] = [];
/**
 * @example
 *
 * Must be called on the top scope of component
 *
 * ```ts
 * const Component = (props: {}) => {
 *   const ctx = getCurrentScene();
 *   return '';
 * };
 * ```
 *
 * DO NOT call on other place
 *
 * ```ts
 * const Component = (props: {}) => {
 *   const fn = () => {
 *     const ctx = getCurrentScene(); // WRONG!
 *   };
 *   return '';
 * };
 * ```
 */
export const getCurrentScene = () =>
  sceneStack[sceneStack.length - 1] ?? ERR('Not found current scene');
// #endregion

// #region adapter
const ReactiveFn = Symbol();
type ComponentFlags = {
  [ReactiveFn]?: <T extends LooseObject>(obj: T) => T;
};
export type ComponentAdapter = {
  /** Mark a component with reactive function */
  mark: <T extends Component>(component: T & ComponentFlags) => T;
  /** Call a component with default props and provided scene */
  render: <T extends Component>(
    component: T & ComponentFlags,
    defaultProps: Parameters<T>[0],
    /** If not provided, use current scene */
    ctx?: Scene<Component>,
  ) => {
    props: Parameters<T>[0];
  } & (ReturnType<T> extends infer R
    ? R extends { node: infer N; data: infer D }
      ? { nodes: N extends NodeLike ? [N] : N; data: D }
      : { nodes: R extends NodeLike ? [R] : R; data: undefined }
    : never);
};
/**
 * Adapte third-part reactive systems
 *
 * @example
 *
 * With Vue
 *
 * ```ts
 * import { shallowReactive, effect } from '@vue/reactivity';
 * const adapter = createComponentAdapter(shallowReactive);
 * const VueComponent = (props: { text: string }) => {
 *   const node = document.createElement('div');
 *   effect(() => (node.textContent = props.text));
 *   return node;
 * };
 * const Component = adapter.mark(VueComponent);
 * ```
 */
export const createComponentAdapter = (
  reactive: <T extends LooseObject>(obj: T) => T,
): ComponentAdapter => ({
  mark(component) {
    component[ReactiveFn] = reactive;
    return component;
  },
  render(component, defaultProps, ctx) {
    const rprops = (component[ReactiveFn] ?? reactive)(defaultProps);

    ctx && sceneStack.push(ctx);
    const instanceOrNode = component(rprops);
    ctx && sceneStack.pop();

    let data: (() => LooseObject) | undefined;
    const nodes = array_normalize(
      typeof instanceOrNode !== 'string' && 'node' in instanceOrNode
        ? ((data = instanceOrNode.data), instanceOrNode.node)
        : instanceOrNode,
    );
    return { props: rprops, nodes, data } as ReturnType<
      ComponentAdapter['render']
    >;
  },
});
// #endregion

// #region event system
/**
 * Lifecycle hooks.
 *
 * | name  | trigger timing                        |
 * | ----- | ------------------------------------- |
 * | show  | the scene is shown                    |
 * | frame | on each frame when the scene is shown |
 * | close | the scene is closed                   |
 */
export type SceneEventMap = {
  show: undefined;
  frame: number;
  close: undefined;
};
// #endregion

// #region scene
/** Scene options */
export type SceneOptions<T extends MaybeGenericComponent> = {
  /** Root element */
  root: HTMLDivElement;
  /** Default props */
  defaultProps: T extends Component<infer P, infer _>
    ? P
    : Parameters<T>[1] & {}; // NOTE: extract GenericComponent's raw props type';
  /** Control show timing */
  timer: () => Timer;
  /** Component adapter */
  adapter: ComponentAdapter;
};
export class Scene<
  T extends MaybeGenericComponent,
> extends EventEmitter<SceneEventMap> {
  readonly root: HTMLDivElement;
  readonly #timer: Timer;
  readonly #props: LooseObject;
  readonly data: T extends MaybeGenericComponent<infer _, infer D>
    ? () => D
    : undefined;
  /**
   * Show DOM and update props one-time
   *
   * @example
   *
   * Basic usage
   *
   * ```ts
   * await scene.show({ text: 'new' }); // show with new props
   * await scene.show(); // show with default props
   * ```
   */
  //@ts-expect-error impl generic show
  show: T extends Component<infer P, infer D>
    ? (patchProps?: Partial<P>) => Promise<Merge<D, BuiltinData>>
    : T = this.#show; // use GenericComponent as Scene.show type

  /**
   * @param component - {@link Component}
   * @param options - {@link SceneOptions}
   */
  constructor(
    component: T,
    public readonly options: SceneOptions<T>,
  ) {
    super();
    const { root, adapter, defaultProps, timer } = options;
    (this.root = root).tabIndex = -1; // support keyboard events
    root.style.scale = '0';

    const { props, nodes, data } = adapter.render(
      //@ts-expect-error impl generic component
      component,
      { ...defaultProps },
      this.on('dispose', () => root.remove()),
    );
    this.#timer = timer(); // create timer instance
    this.#props = props;
    //@ts-expect-error impl generic component
    this.data = data;
    root.append(...nodes);
  }
  /**
   * If called in frame, close in current frame (as microtask), else in next
   * frame
   */
  close() {
    const ref = this.#timer; // NOTE: keep timer ref
    (currentFrameTime ? queueMicrotask : rAF)(() => ref.stop());
  }
  async #show(patchProps?: Partial<LooseObject>) {
    const { root, defaultProps } = this.options;

    // modify props
    const newProps = { ...defaultProps, ...patchProps };
    for (const key of Object.keys({ ...this.#props, ...newProps }))
      this.#props[key] = newProps[key];

    // show
    this.emit('show');
    root.style.scale = '1';
    root.focus();

    // wait timer
    const records = await this.#timer.start((time) => this.emit('frame', time));

    // close
    root.style.scale = '0';
    return {
      ...this.emit('close').data?.(),
      frame_times: records,
      duration: currentFrameTime - records[0]!,
    } satisfies BuiltinData;
  }
}
// #endregion
