name: E2E Tests
description: 'Start local server and run Playwright E2E tests'
runs:
  using: 'composite'
  steps:
    - run: bunx playwright install --with-deps
      shell: bash
    - run: |
        python3 -m http.server -d dist 3000 &
        bunx wait-on http://127.0.0.1:3000
      shell: bash
    - run: bun run e2e tests
      shell: bash
