name: CD
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'should deploy'
        require: false
        type: boolean
        default: true
      publish:
        description: 'should publish'
        require: false
        type: boolean
        default: true
      dev:
        description: 'dev mode'
        require: false
        type: boolean
        default: false
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/configure-pages@v6
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy || true }}
      - run: bun ci
      - run: bun run build
      - uses: ./.github/actions/e2e
      - uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy || true }}
        with:
          path: dist

  deploy:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy || true }}
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.publish || true }}
    runs-on: ubuntu-24.04
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run publish ${{ inputs.dev && ' --dev' || '' }}
