name: CI
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build-pages:
    timeout-minutes: 3
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/configure-pages@v4
      - run: bun ci
      - run: bun run build
      - uses: ./.github/actions/e2e
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy-pages:
    needs: build-pages
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish-npm:
    if: contains(github.ref, 'refs/tags/')
    needs: build-pages
    runs-on: ubuntu-24.04
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run publish
